# kubectl create deployment appbackend --image=maiok/incubator2024-appbackend --port=8080 --replicas=1 --dry-run=client -o yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: appbackend
  name: appbackend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appbackend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: appbackend
    spec:
      containers:
      - image: maiok/incubator2024-appbackend
        name: incubator2024-appbackend
        ports:
        - containerPort: 9080
        resources: {}
        env:
          - name: MONGO_CONN_STR
            value: "mongodb://mongodb:27017/platformsdb"
          - name: MONGO_USERNAME
            value: "root"
          - name: MONGO_PASSWORD
            value: "Incubator2024"
status: {}