# kubectl create service clusterip service-appbackend --tcp=8081:9080 --dry-run -o yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: service-appbackend
  name: service-appbackend
spec:
  ports:
  - name: 8081-9080
    port: 8081
    protocol: TCP
    targetPort: 9080
  selector:
    app: appbackend
  type: NodePort
status:
  loadBalancer: {}